#!/usr/bin/env bash

PROVIDER="$(echo ${LENSES_SECRET_PROVIDER} | tr '[A-Z]' '[a-z]')"
TYPE="$(echo ${LENSES_APP_TYPE} | tr '[A-Z]' '[a-z]')"
MOUNT_PATH=${MOUNT_PATH:-"/mnt/shared-data"}



# Azure key vault
if [[ ${PROVIDER} == "azure" ]]; then

    if [[ ${TYPE} == "connect" ]]; then 
        lenses-cli \
        secrets connect azure \
        --secret-file ${MOUNT_PATH}/secret.props \
        --tenant-id ${AZURE_TENANT_ID} \
        --client-id ${AZURE_CLIENT_ID} \
        --client-secret ${AZURE_CLIENT_SECRET} \
        --vault-name ${AZURE_KEYVAULT_NAME} \
        --worker-file ${MOUNT_PATH}/worker.props \
        --connector-file ${MOUNT_PATH}/connector.props
    else
        lenses-cli \
        secrets app azure \
        --secret-file ${MOUNT_PATH}/secret.props \
        --tenant-id ${AZURE_TENANT_ID} \
        --client-id ${AZURE_CLIENT_ID} \
        --client-secret ${AZURE_CLIENT_SECRET} \
        --vault-name ${AZURE_KEYVAULT_NAME} 
    fi 

# HashiCorp vault
elif [[ ${PROVIDER} == "vault" ]]; then
    if [[ ${TYPE} == "connect" ]]; then 
        lenses-cli \
        secrets connect vault \
        --vault-server ${VAULT_SERVER} \
        --vault-role ${VAULT_ROLE} \
        --vault-token ${VAULT_TOKEN} \
        --secret-file ${MOUNT_PATH}/secret.props \
        --worker-file ${MOUNT_PATH}/worker.props \
        --connector-file ${MOUNT_PATH}/connector.props
    else
        lenses-cli \
        secrets app vault \
        --vault-server ${VAULT_SERVER} \
        --vault-role ${VAULT_ROLE} \
        --vault-token ${VAULT_TOKEN} \
        --secret-file ${MOUNT_PATH}/secret.props
    fi 
fi